FROM phusion/passenger-ruby21:0.9.8
ENV HOME /root

PREADD app/presetup /tmp/presetup
PRERUN /tmp/presetup && rm /tmp/presetup

RUN /app/setup app && apt-get clean

VOLUME ["/var/lib/postgresql"]
CMD ["/sbin/my_init"]
