#!/usr/bin/env ruby
require 'socket'
require 'base64'

app_dir = ARGV.shift

if ENV['CONTAINER_PORT']
	port = ENV['CONTAINER_PORT'].to_i
else
	container = `docker run -d -h=apachai-hopachai -u=appa -p 3002 apachai-hopachai sudo -u appa /usr/local/rvm/bin/rvm-exec 1.9.3 ruby /runner`.strip
	port = `docker port #{container} 3002`.to_i
	sleep 1
end

#puts "Connecting to container through forwarded port #{port}"
sock = TCPSocket.new('127.0.0.1', port)
sock.sync = true
sock.binmode

sock.write(Base64.strict_encode64(Marshal.dump(
	:args => ARGV
)))
sock.write("\n")

Dir.chdir(app_dir)
IO.popen("tar -c . | gzip --best", "r") do |io|
	while !io.eof?
		buf = io.read(1024 * 32)
		sock.write(Base64.strict_encode64(buf))
		sock.write("\n")
	end
	sock.write("\n")
end

#puts "Receiving output..."
while true
	line = sock.readline
	break if line == "\n"
	buf = Base64.decode64(line)
	STDOUT.write(buf)
	STDOUT.flush
end

sock.close

if container
	system("docker kill #{container}")
	system("docker rm #{container}")
end
