#!/usr/bin/env ruby
require 'logger'
require 'yaml'

def sh(command, *args)
	puts "$ #{command} #{args.join(' ')}"
	if !system(command, *args)
		abort "*** Command failed with code #{$? ? $?.exitstatus : 'unknown'}"
	end
end

def log(message)
	puts "# #{message}"
end

def run_command_list(commands)
	return if !commands
	commands.each do |command|
		sh command
	end
end

def run_script(config)
	if config['env']
		sh "env #{config['env']} #{config['script']}"
	else
		sh config['script']
	end
end

def start
	config = YAML.load_file('travis.yml')
	Dir.chdir("app")
	run_command_list(config['before_install'])
	run_script(config)
	log "Apachai Hopachai finished."
end

ENV['TERM'] = 'xterm-256color'
ENV['LANG'] = 'en_US.UTF-8'
ENV['LC_ALL'] = 'en_US.UTF-8'
ENV['RUBYOPT'] = '-Eutf-8'

if ARGV[0] == "--dry-run"
	puts "--dry-run given, stopping."
else
	start
end

