#!/bin/bash
set -e
source /etc/environment
user=`stat -L --printf %U /appa`
cd /appa/webui
export RAILS_ENV=${RAILS_ENV:-development}
status=`/sbin/setuser $user passenger status`
if echo "$status" | grep -q "is running"; then
	/sbin/setuser $user passenger stop
fi
exec /sbin/setuser $user passenger start -e $RAILS_ENV
