#!/bin/bash
set -e
cd /app/webui
touch log/sidekiq.log
chown app: log/sidekiq.log
export JOB_CONCURRENCY=${JOB_CONCURRENCY:-2}
exec /sbin/setuser app /app/bin/sidekiq \
	-C ../config/sidekiq.yml \
	-c $JOB_CONCURRENCY \
	-l log/sidekiq.log \
	-e $RAILS_ENV \
	>>log/sidekiq.log 2>&1
