#!/bin/bash
set -e
source /etc/environment
cd /app/webui
export RAILS_ENV=${RAILS_ENV:-development}
status=`/sbin/setuser app passenger status`
if echo "$status" | grep -q "is running"; then
	/sbin/setuser app passenger stop || true
fi
exec /sbin/setuser app passenger start -e $RAILS_ENV
