#!/bin/bash
set -e
source /etc/environment
cd /app/webui
export JOB_CONCURRENCY=${JOB_CONCURRENCY:-2}
export RAILS_ENV=${RAILS_ENV:-development}
exec /sbin/setuser app /appa/bin/sidekiq \
	-C ../config/sidekiq.yml \
	-c $JOB_CONCURRENCY \
	-l log/sidekiq.log \
	-e $RAILS_ENV \
	>>log/sidekiq.log 2>&1
