#!/bin/bash
set -e

function cleanup()
{
	local pids=`jobs -p`
	if [[ "$builddir" != "" ]]; then
		rm -rf "$builddir"
	fi
	if [[ "$pids" != "" ]]; then
		kill $pids
	fi
}

trap cleanup EXIT

eval "$(./dade/dump.rb Dadefile)"

# List all app files.
IFS=$'\n'
app_files=(`./dade/list_files.rb "$DADEFILE_APP_DIR_PATH"`)
unset IFS

# Create temporary build directory for 'docker build'.
builddir=`mktemp -d /tmp/dade.XXXXXXX`
./dade/copy_files.rb "$DADEFILE_APP_DIR_PATH" "${app_files[@]}" "$builddir/$DADEFILE_APP_DIR_CONTAINER_BUILD_PATH"

# Preprocess Dockerfile and put it in the build directory.
./dade/process_dockerfile_dade.rb "$DADEFILE_DOCKERFILE_DADE" "$DADEFILE_APP_DIR_CONTAINER_BUILD_PATH" > \
	"$builddir/Dockerfile"

# Run 'docker build'.
pushd "$builddir"
docker build -t "$DADEFILE_NAME:$DADEFILE_VERSION.dev" .
