#!/bin/bash
set -e

function cleanup()
{
	local pids=`jobs -p`
	if [[ "$builddir" != "" ]]; then
		rm -rf "$builddir"
	fi
	if [[ "$pids" != "" ]]; then
		kill $pids
	fi
}

trap cleanup EXIT

CONTAINER_NAME=${CONTAINER_NAME:-my/dadeapp:dev}

# List all app files.
IFS=$'\n'
files=(`./dade/list_files.rb app`)
unset IFS

# Create temporary build directory for 'docker build'.
builddir=`mktemp -d /tmp/dade.XXXXXXX`
./dade/copy_files.rb "${files[@]}"  "$builddir"

# Preprocess Dockerfile and put it in the build directory.
cp app/Dockerfile "$builddir/"

# Run 'docker build'.
pushd "$builddir"
docker build -t $CONTAINER_NAME .
