#!/usr/bin/env ruby
require 'logger'
require 'base64'

REPO_URL = ARGV[0]
CONFIG   = Marshal.load(Base64.decode64(ARGV[1]))

def sh(command, *args)
	puts "$ #{command} #{args.join(' ')}"
	if !system(command, *args)
		abort "*** Command failed with code #{$? ? $?.exitstatus : 'unknown'}"
	end
end

def log(message)
	puts "# #{message}"
end

def run_command_list(commands)
	return if !commands
	commands.each do |command|
		sh command
	end
end

def run_script(config)
	if config['env']
		sh "env #{config['env']} #{config['script']}"
	else
		sh config['script']
	end
end

def start
	ENV['TERM'] = 'xterm-256color'
	Dir.chdir("app")
	run_command_list(CONFIG['before_install'])
	run_script(CONFIG)
	log "Apachai Hopachai finished."
end

start
