#!/usr/bin/env ruby
STDOUT.reopen("log.txt", "a")
STDERR.reopen(STDOUT)
STDOUT.sync = STDERR.sync = true

require 'yaml'
require 'logger'

REPO_URL = ARGV[0]

def sh(command, *args)
	log "#{command} #{args.join(' ')}"
	if !system(command, *args)
		abort "*** Command failed with code #{$? ? $?.exitstatus : 'unknown'}"
	end
end

def log(message)
	puts "# #{message}"
end

def clone_and_activate_repo
	sh "git clone #{REPO_URL} repo"
	log "cd repo"
	Dir.chdir(REPO_URL)
end

def read_config
	log "Reading .travis.yml"
	return YAML.load_file(".travis.yml")
end

def run_command_list(commands)
	return if !commands
	commands.each do |command|
		sh command
	end
end

def run_script_with_env(config, env)
	if env.empty?
		sh config['script']
	else
		sh "env #{env} #{config['script']}"
	end
end

def run_script(config)
	environments = config['env'] || ['']
	environments.each do |env|
		run_script_with_env(config, env)
	end
end

def start
	clone_and_activate_repo
	config = read_config
	run_command_list(config['before_install'])
	run_script(config)
	log "Apachai Hopachai finished."
end

start
