source 'https://rubygems.org'

gem 'safe_yaml'

group :models do
  gem 'rails', '~> 4.0.2'
  gem 'pg'
  gem 'cancan'
  gem 'devise'
  gem 'schema_plus'
  gem 'simple_enum'
  gem 'default_value_for'
  gem 'acts_as_list'
  gem 'sidekiq'
end

group :cli do
  gem 'ansi2html'
  gem 'mail'
end

group :webui do
  gem 'sass-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'jquery-rails'
  gem 'turbolinks'
  gem 'jbuilder', '~> 1.2'
  gem 'bootstrap-sass', '>= 3.0.0.0'
  gem 'simple_form'
  gem 'sinatra', '>= 1.3.0', :require => nil
  # For Rails 4 support.
  gem 'activeadmin', :github => 'gregbell/active_admin'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :mri_21, :rbx]
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end
