#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive

function apt_get_install()
{
	apt-get install -q -y --force-yes --no-install-recommends "$@"
}

set -x

# Add APT sources.
if ! [[ -e /etc/apt/sources.list.d/docker.list ]]; then
	if ! [[ -e /usr/bin/wget ]]; then
		apt-get update
		apt_get_install wget
	fi
	wget -q -O - https://get.docker.io/gpg | apt-key add -
	echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
fi

# Install software.
apt-get update
apt_get_install lxc-docker cgroup-lite git postfix inotify-tools libpq-dev postgresql

# Setup Docker.
usermod -a -G docker app
