#!/bin/bash
set -e

TARGET_USER="$1"

if [[ "$TARGET_USER" = "" ]]; then
	echo "Usage: ./setup <TARGET USER>"
	exit 1
fi

if [[ "`id -u`" != 0 ]]; then
	echo "This script must be run as root."
	exit 1
fi

function apt_get_install()
{
	apt-get install -q -y --force-yes --no-install-recommends "$@"
}

export DEBIAN_FRONTEND=noninteractive
SELFDIR=`dirname "$0"`
if [[ "$TARGET_USER" = vagrant ]]; then
	BUNDLE_PATH=
else
	BUNDLE_PATH="--path vendor"
fi

set -x

cd "$SELFDIR"
apt_get_install git postfix inotify-tools
sudo -u "$TARGET_USER" -H bundle install $BUNDLE_PATH
