#!/usr/bin/env ruby
require 'socket'
require 'fileutils'
Dir.chdir('/home/appa')

puts "Waiting for input..."
server = TCPServer.new('0.0.0.0', 3002)
client = server.accept

puts "Receiving input"
input = File.open('input.tar.gz', 'wb')
while !client.eof?
	buf = client.read(1024 * 32)
	input.write(buf)
end
input.close

puts "Extracting input"
FileUtils.rm_rf("work")
Dir.mkdir("work")
Dir.chdir("work")
if !system("tar xzf ../input.tar.gz")
	abort "runner: Cannot extract payload"
end
File.unlink("../input.tar.gz")

puts "Running input"
if !system("./main")
	abort "runner: Error running input"
end

puts "Packaging output"
if !system("tar -c . > ../output.tar")
	abort "runner: Error creating tarball"
end
Dir.chdir("..")
if !system("gzip -f --best output.tar")
	abort "runner: Error gzipping tarball"
end

puts "Sending output"
output = File.open("output.tar.gz", "rb")
while !output.eof?
	buf = output.read(1024 * 32)
	client.write(buf)
end
output.close
File.unlink("output.tar.gz")

puts "Done"
client.close
